<?php
return [
	'forums'   => 'Forums',
	'home'     => 'Home',
	'logged'   => [
		'in' => [
			'logout'        => 'Logout',
			'messenger'     => 'Messenger',
			'my_profile'    => 'My Profile',
			'my_settings'   => 'My Settings',
			'notifications' => 'Notifications',
		],
		'out' => [
			'login'  => 'Login',
			'signup' => 'Sign Up',
		],
	],
	'menu'     => 'Menu',
	'radio'    => 'Radio',
	'runescape' => [
		'title'             => 'Runescape',
		'calculators'       => 'Calculators',
		'combat_calculator' => 'Combat Calculator',
		'name_checker'      => 'Name Checker',
		'play'              => 'Play Runescape',
	],
	'runetime' => [
		'title'      => 'RuneTime',
		'about_us'   => 'About Us',
		'awards'     => 'Awards',
		'members'    => 'Members',
		'news'       => 'News',
		'signatures' => 'Signature Generator',
		'staff_list' => 'Staff List',
		'tickets'    => 'Tickets',
	],
	'social' => [
		'title'        => 'Social',
		'calendar'     => 'Event Calendar',
		'livestream'   => 'Livestream',
		'members_map'  => 'Members Map',
		'our_clan'     => 'Our Clan',
		'social_media' => 'Social Media',
	],
	'staff' => [
		'title'         => 'Staff',
		'administrator' => 'Administrator Panel',
		'content'       => 'Content Panel',
		'checkup'       => 'Staff Checkup',
		'events'        => 'Events Panel',
		'gallery'       => 'Gallery',
		'radio'         => 'Radio Panel',
		'staff'         => 'Staff',
		'staff_panel'   => 'Staff Panel',
		'team_leader'   => 'Team Leader Panel',
		'ticket'        => 'Ticket System',
	],
	'toggle_navigation' => 'Toggle Navigation',
];
